<?php

$GLOBALS['pumpform_config']['user']['payment_monthly_stripe_customer'] = array(
    'module' => 'user',
    'title' => 'payment_monthly_stripe_customer',
    'table' => 'payment_monthly_stripe_customer',

    'column' => array(

        'user_id' => array('name' => 'user_id',
                         'type' => PUMPFORM_INT,
                         'title' => 'user_id',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'customer_id' => array('name' => 'customer_id',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'customer_id',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'account_balance' => array('name' => 'account_balance',
                         'type' => PUMPFORM_INT,
                         'title' => 'account_balance',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'created' => array('name' => 'created',
                         'type' => PUMPFORM_INT,
                         'title' => 'created',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'currency' => array('name' => 'currency',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'currency',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'email' => array('name' => 'email',
                         'type' => PUMPFORM_EMAIL,
                         'title' => 'email',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'card_id' => array('name' => 'card_id',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'card_i',
                         'required' => 0,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        ),
);

$GLOBALS['pumpform_config']['user']['payment_monthly_stripe_subscription'] = array(
    'module' => 'user',
    'title' => 'payment_monthly_stripe_subscription',
    'table' => 'payment_monthly_stripe_subscription',

    'column' => array(

        'user_id' => array('name' => 'user_id',
                         'type' => PUMPFORM_INT,
                         'title' => 'user_id',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'subscription_id' => array('name' => 'subscription_id',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'subscription_id',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'billing' => array('name' => 'billing',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'billing',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'cancel_at_period_end' => array('name' => 'cancel_at_period_end',
                         'type' => PUMPFORM_INT,
                         'title' => 'cancel_at_period_end',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'canceled_at' => array('name' => 'canceled_at',
                         'type' => PUMPFORM_INT,
                         'title' => 'canceled_at',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'created' => array('name' => 'created',
                         'type' => PUMPFORM_INT,
                         'title' => 'created',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'current_period_end' => array('name' => 'current_period_end',
                         'type' => PUMPFORM_INT,
                         'title' => 'current_period_end',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'current_period_start' => array('name' => 'current_period_start',
                         'type' => PUMPFORM_INT,
                         'title' => 'current_period_start',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'customer_id' => array('name' => 'customer_id',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'customer_id',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'ended_at' => array('name' => 'ended_at',
                         'type' => PUMPFORM_INT,
                         'title' => 'ended_at',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'subscription_item_id' => array('name' => 'subscription_item_id',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'subscription_item_id',
                         'required' => 0,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        'plan_id' => array('name' => 'plan_id',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'plan_id',
                         'required' => 0,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 0,),
        ),
);
