<?php

$pumpform_config['image']['image'] = array(
    'module' => 'image',
    'title' => _MD_IMAGE_IMAGE_TITLE,
    'table' => 'image',

	'list_php' => 'list',

    'column' => array(
        array('name' => 'id',
	      'type' => PUMPFORM_PRIMARY_ID,
	      'visible' => 0),
        array('name' => 'site_id',
              'type' => PUMPFORM_SITE_ID,
              'visible' => 0),
        array('name' => 'reg_time',
              'type' => PUMPFORM_TIME,
              'visible' => 0),
        array('name' => 'mod_time',
              'type' => PUMPFORM_TIME,
              'visible' => 0),
        array('name' => 'reg_user',
              'type' => PUMPFORM_USER,
              'visible' => 0),
        array('name' => 'mod_user',
              'type' => PUMPFORM_USER,
              'visible' => 0),
		      
	array('name' => 'width',
	      'title' => _MD_IMAGE_WIDTH,
	      'type' => PUMPFORM_INT,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 0,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'height',
	      'title' => _MD_IMAGE_HEIGHT,
	      'type' => PUMPFORM_INT,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 0,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'type',
	      'title' => _MD_IMAGE_TYPE,
	      'type' => PUMPFORM_INT,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 1,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'code',
	      'title' => _MD_IMAGE_CODE,
	      'type' => PUMPFORM_TEXT,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 1,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'public',
	      'title' => _MD_IMAGE_PUBLIC,
	      'type' => PUMPFORM_BOOLEAN,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 0,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'ip_address',
	      'title' => _MD_IMAGE_IPADDRESS,
	      'type' => PUMPFORM_IPADDRESS,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 0,
	      'editable' => 0,
	      'list_visible' => 0,),
	/*
        array('name' => 'title',
              'title' => _MD_IMAGE_TITLE,
	      'type' => PUMPFORM_TEXT,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'minlength' => 1,
	      'maxlength' => 64),
	array('name' => 'desc',
	      'title' => _MD_IMAGE_DESC,
	      'type' => PUMPFORM_TEXTAREA,
	      'cols' => 50,
	      'rows' => 5,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'minlenth' => 3,
	      'maxlength' => 10000),
  */
	),
);
					 
