<?php

$pumpform_config['image']['image'] = array(
    'module' => 'image',
    'title' => _MD_IMAGE_IMAGE_TITLE,
    'table' => 'image',

    'list_php' => 'list',
    'detail_php' => 'detail',

    'default_sort' => 'd_id',
    'editable' => 0,

    'column' => array(

    'width' => array('name' => 'width',
          'title' => _MD_IMAGE_WIDTH,
          'type' => PUMPFORM_INT,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 0,
          'list_visible' => 1,),
    'height' => array('name' => 'height',
          'title' => _MD_IMAGE_HEIGHT,
          'type' => PUMPFORM_INT,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 0,
          'list_visible' => 1,),
    'type' => array('name' => 'type',
          'title' => _MD_IMAGE_TYPE,
          'type' => PUMPFORM_INT,
          'required' => 0,
          'visible' => 0,
          'registable' => 1,
          'editable' => 0,
          'list_visible' => 0,),
    'code' => array('name' => 'code',
          'title' => _MD_IMAGE_CODE,
          'type' => PUMPFORM_TEXT,
          'required' => 0,
          'visible' => 0,
          'registable' => 1,
          'editable' => 0,
          'list_visible' => 1,),
    'public' => array('name' => 'public',
          'title' => _MD_IMAGE_PUBLIC,
          'type' => PUMPFORM_BOOLEAN,
          'required' => 0,
          'visible' => 0,
          'registable' => 0,
          'editable' => 0,
          'list_visible' => 0,),
    'ip_address' => array('name' => 'ip_address',
          'title' => _MD_IMAGE_IPADDRESS,
          'type' => PUMPFORM_IPADDRESS,
          'required' => 0,
          'visible' => 0,
          'registable' => 0,
          'editable' => 0,
          'list_visible' => 0,),
    ),
);
                     
