<?php

$pumpform_config['file']['file'] = array(
    'module' => 'file',
    'title' => 'file',
    'table' => 'file',

	'list_php' => 'list',

    'column' => array(

	array('name' => 'type',
	      'title' => _MD_FILE_TYPE,
	      'type' => PUMPFORM_INT,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 1,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'code',
	      'title' => _MD_FILE_CODE,
	      'type' => PUMPFORM_TEXT,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 1,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'public',
	      'title' => _MD_FILE_PUBLIC,
	      'type' => PUMPFORM_BOOLEAN,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 0,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'ip_address',
	      'title' => _MD_FILE_IPADDRESS,
	      'type' => PUMPFORM_IPADDRESS,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 0,
	      'editable' => 0,
	      'list_visible' => 0,),
	array('name' => 'size',
	      'title' => 'size',
	      'type' => PUMPFORM_INT,
	      'required' => 0,
	      'visible' => 0,
	      'registable' => 1,
	      'editable' => 0,
	      'list_visible' => 0,),
        array('name' => 'filename',
              'title' => _MD_FILE_TITLE,
	      'type' => PUMPFORM_TEXT,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'minlength' => 1,
	      'maxlength' => 64),
	),
);
					 
