<?php

$pumpform_config['admin']['config'] = array(
	'module' => 'admin',
	'title' => 'config',
	'table' => 'config',
	'column' => array(
		array('name' => 'id',
			'type' => PUMPFORM_PRIMARY_ID,
			'visible' => 0),
		array('name' => 'site_id',
			'type' => PUMPFORM_SITE_ID,
			'visible' => 0),
		array('name' => 'reg_time',
			'type' => PUMPFORM_TIME,
			'visible' => 0),
		array('name' => 'mod_time',
			'type' => PUMPFORM_TIME,
			'visible' => 0),
		array('name' => 'reg_user',
			'type' => PUMPFORM_USER,
			'visible' => 0),
		array('name' => 'mod_user',
			'type' => PUMPFORM_USER,
			'visible' => 0),

		'name' => array('name' => 'name',
			'title' => 'name',
			'type' => PUMPFORM_TEXT,
			'visible' => 1,
			'registable' => 1,
			'editable' => 1,
			'list_visible' => 1,),
		'value' => array('name' => 'value',
			'title' => 'value',
			'type' => PUMPFORM_TEXT,
			'visible' => 1,
			'registable' => 1,
			'editable' => 1,
			'list_visible' => 1,),
    ),
);


$pumpform_config['admin']['config_form'] = array(
	'module' => 'admin',
	'title' => 'config',
	'table' => 'config_form',
	'column' => array(
		array('name' => 'id',
			'type' => PUMPFORM_PRIMARY_ID,
			'visible' => 0),
		array('name' => 'site_id',
			'type' => PUMPFORM_SITE_ID,
			'visible' => 0),
		array('name' => 'reg_time',
			'type' => PUMPFORM_TIME,
			'visible' => 0),
		array('name' => 'mod_time',
			'type' => PUMPFORM_TIME,
			'visible' => 0),
		array('name' => 'reg_user',
			'type' => PUMPFORM_USER,
			'visible' => 0),
		array('name' => 'mod_user',
			'type' => PUMPFORM_USER,
			'visible' => 0),

		'title' => array('name' => 'site_title',
			'title' => 'site_title',
			'type' => PUMPFORM_TEXT,
			'visible' => 1,
			'registable' => 1,
			'editable' => 1,
			'list_visible' => 1,),
		'description' => array('name' => 'description',
			'title' => 'description',
			'type' => PUMPFORM_TEXTAREA,
			'visible' => 1,
			'registable' => 1,
			'editable' => 1,
			'list_visible' => 1,),
		'debag_mode' => array('name' => 'debug_mode',
			'title' => 'debug_mode',
			'type' => PUMPFORM_SELECT,
			//'placeholder' => _MD_SHOP_STATUS,
			'required' => 0,
			'visible' => 1,
			'registable' => 1,
			'editable' => 1,
			'list_visible' => 0,
			'option' => array(
				0 => 'off',
				1 => 'on',
				)
			),
		'site_close' => array('name' => 'site_close',
			'title' => 'site_close',
			'type' => PUMPFORM_SELECT,
			//'placeholder' => _MD_SHOP_STATUS,
			'required' => 0,
			'visible' => 1,
			'registable' => 1,
			'editable' => 1,
			'list_visible' => 0,
			'option' => array(
				0 => 'open',
				1 => 'close',
				)
			),
    ),
);



