<?php

$pumpform_config['link']['link'] = array(
    'module' => 'link',
    'title' => 'link',
    'table' => 'link',

    'list_limit' => 10,
    'default_sort' => 'd_id',
					 
    'list_php' => 'list',
    'detail_php' => 'detail',

    'grant_index' => [ 'anonymous' => 1, 'registerd_user' => 1, 'posted_user' => 1],
    'grant_detail' => [ 'anonymous' => 1, 'registered_user' => 1, 'posted_user' => 1],
    'grant_add' => [ 'anonymous' => 0, 'registered_user' => 1, 'posted_user' => 1 ], 
    'grant_update' =>  [ 'anonymous' => 0, 'registered_user' => 0, 'posted_user' => 1 ],
    'grant_delete' =>  [ 'anonymous' => 0, 'registered_user' => 0, 'posted_user' => 1 ],

    'column' => array(

	array('name' => 'title',
	      'title' => 'サイトタイトル',
	      'type' => PUMPFORM_TEXT,
	      'required' => 1,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'minlenth' => 3,
	      'maxlength' => 200),
	'url' => array('name' => 'url',
	      'title' => 'URL',
	      'type' => PUMPFORM_URL,
	      'required' => 1,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'minlength' => 3,	   
	      'maxlength' => 255),
	array('name' => 'desc',
	      'title' => '説明',
	      'type' => PUMPFORM_TEXTAREA,
	      'cols' => 50,
	      'rows' => 5,
	      'required' => 1,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'minlenth' => 3,
	      'maxlength' => 2000),
	array('name' => 'tag',
	      'title' => 'タグ',
	      'type' => PUMPFORM_TAG,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1),
	array('name' => 'screenshot1',
	      'title' => 'サイトサムネイル',
	      'type' => PUMPFORM_IMAGE,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'crop' => 1),
	array('name' => 'screenshot2',
	      'title' => 'サイトサムネイル',
	      'type' => PUMPFORM_IMAGE,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'crop' => 1),
	array('name' => 'screenshot3',
	      'title' => 'サイトサムネイル',
	      'type' => PUMPFORM_IMAGE,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'crop' => 1),
	array('name' => 'screenshot4',
	      'title' => 'サイトサムネイル',
	      'type' => PUMPFORM_IMAGE,
	      'required' => 0,
	      'visible' => 1,
	      'registable' => 1,
	      'editable' => 1,
	      'list_visible' => 1,
	      'crop' => 1),

    ),		      
);
					 
