<?php

$pumpform_config['link']['link'] = array(
    'module' => 'link',
    'title' => 'link',
    'table' => 'link',

    'list_limit' => 10,
    'default_sort' => 'd_id',

    'list_php' => 'list',
    'detail_php' => 'detail',

    'grant' => 1,
                     
    'column' => array(

    array('name' => 'title',
          'title' => 'サイトタイトル',
          'type' => PUMPFORM_TEXT,
          'required' => 1,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'minlenth' => 3,
          'maxlength' => 200),
    'url' => array('name' => 'url',
          'title' => 'URL',
          'type' => PUMPFORM_URL,
          'required' => 1,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'minlength' => 3,       
          'maxlength' => 255),
    array('name' => 'desc',
          'title' => '説明',
          'type' => PUMPFORM_TEXTAREA,
          'cols' => 50,
          'rows' => 5,
          'required' => 1,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'minlenth' => 3,
          'maxlength' => 2000),
    array('name' => 'tag',
          'title' => 'タグ',
          'type' => PUMPFORM_TAG,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'tag_table' => 'tag',
          'tag_rel_table' => 'tag_rel'),
    array('name' => 'screenshot1',
          'title' => 'サイトサムネイル',
          'type' => PUMPFORM_IMAGE,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'crop' => 1),
    array('name' => 'screenshot2',
          'title' => 'サイトサムネイル',
          'type' => PUMPFORM_IMAGE,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'crop' => 1),
    array('name' => 'screenshot3',
          'title' => 'サイトサムネイル',
          'type' => PUMPFORM_IMAGE,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'crop' => 1),
    array('name' => 'screenshot4',
          'title' => 'サイトサムネイル',
          'type' => PUMPFORM_IMAGE,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'crop' => 1),

    ),
);

$pumpform_config['link']['tag'] = array(
    'module' => 'link',
    'title' => 'tag',
    'table' => 'tag',

    'list_limit' => 10,
    'default_sort' => 'd_id',
                     
    'column' => array(

    array('name' => 'tag',
          'title' => 'tag',
          'type' => PUMPFORM_TEXT,
          'required' => 1,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1,
          'minlenth' => 0,
          'maxlength' => 255),
    array('name' => 'count',
          'title' => 'count',
          'type' => PUMPFORM_INT,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1),

    ),
);

$pumpform_config['link']['tag_rel'] = array(
    'module' => 'link',
    'title' => 'tag_rel',
    'table' => 'tag_rel',

    'list_limit' => 10,
    'default_sort' => 'd_id',
                     
    'column' => array(

    array('name' => 'link_id',
          'title' => 'link_id',
          'type' => PUMPFORM_INT,
          'required' => 1,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1),
    array('name' => 'tag_id',
          'title' => 'tag_id',
          'type' => PUMPFORM_INT,
          'required' => 0,
          'visible' => 1,
          'registable' => 1,
          'editable' => 1,
          'list_visible' => 1),

    ),
);
