<?php

$GLOBALS['pumpform_config']['user']['payment_monthly_paypal_user'] = array(
    'module' => 'user',
    'title' => 'payment_monthly_paypal_user',
    'table' => 'payment_monthly_paypal_user',

    'column' => array(

        'user_id' => array('name' => 'user_id',
                         'type' => PUMPFORM_INT,
                         'title' => 'user_id',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'payerid' => array('name' => 'payerid',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'payerid',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'profileid' => array('name' => 'profileid',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'profileid',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'del_time' => array('name' => 'del_time',
                         'type' => PUMPFORM_INT,
                         'title' => 'del_time',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,
						 'default' => 0),
        ),
);

$GLOBALS['pumpform_config']['user']['payment_monthly_paypal_log'] = array(
    'module' => 'user',
    'title' => 'payment_monthly_paypal_log',
    'table' => 'payment_monthly_paypal_log',

    'column' => array(

        'user_id' => array('name' => 'user_id',
                         'type' => PUMPFORM_INT,
                         'title' => 'user_id',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'method' => array('name' => 'method',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'method',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'token' => array('name' => 'token',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'token',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'payerid' => array('name' => 'payerid',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'payerid',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'profileid' => array('name' => 'profileid',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'profileid',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'profilestatus' => array('name' => 'profilestatus',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'profilestatus',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'timestamp' => array('name' => 'timestamp',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'timestamp',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'correlationid' => array('name' => 'correlationid',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'correlationid',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'ack' => array('name' => 'ack',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'ack',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'version' => array('name' => 'version',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'version',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        'build' => array('name' => 'build',
                         'type' => PUMPFORM_TEXT,
                         'title' => 'build',
                         'required' => 1,
                         'visible' => 1,
                         'registable' => 1,
                         'editable' => 1,
                         'list_visible' => 1,),
        ),
);
